# Generated by Django 3.0.5 on 2020-04-26 17:28

import Nano.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classname', models.CharField(default='전자기학', max_length=50)),
                ('Text', models.TextField(max_length=500000)),
                ('Image', models.ImageField(upload_to=Nano.models.user_path)),
                ('Thumname_image', models.ImageField(blank=True, upload_to='')),
                ('Comment', models.CharField(max_length=255)),
            ],
        ),
    ]
