# Generated by Django 3.0.5 on 2020-05-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nano', '0002_auto_20200427_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_id', models.CharField(max_length=30)),
                ('problem', models.ImageField(upload_to='solutionimg')),
                ('solution', models.TextField()),
                ('rating', models.IntegerField(choices=[('1', '★☆☆☆☆'), ('2', '★★☆☆☆'), ('3', '★★★☆☆'), ('4', '★★★★☆'), ('5', '★★★★★')])),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SummaryImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='summaryimg')),
                ('figure', models.TextField()),
                ('descript', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WordDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WordImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='wordimg')),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='Descript',
        ),
        migrations.DeleteModel(
            name='Descript',
        ),
    ]
