# Generated by Django 3.0.5 on 2020-05-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nano', '0004_auto_20200526_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='id',
        ),
        migrations.AlterField(
            model_name='summary',
            name='title',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
